# ruff: ignore
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hand_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "hand_stream.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11hand_stream.proto\x12\x0borca_teleop"H\n\tHandFrame\x12\x11\n\tkeypoints\x18\x01 \x03(\x02\x12\x12\n\nhandedness\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03""\n\x0cStreamConfig\x12\x12\n\nhandedness\x18\x01 \x01(\t"(\n\rStreamSummary\x12\x17\n\x0f\x66rames_received\x18\x01 \x01(\x03\x32V\n\nHandStream\x12H\n\x10StreamHandFrames\x12\x16.orca_teleop.HandFrame\x1a\x1a.orca_teleop.StreamSummary(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hand_stream_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HANDFRAME"]._serialized_start = 34
    _globals["_HANDFRAME"]._serialized_end = 106
    _globals["_STREAMCONFIG"]._serialized_start = 108
    _globals["_STREAMCONFIG"]._serialized_end = 142
    _globals["_STREAMSUMMARY"]._serialized_start = 144
    _globals["_STREAMSUMMARY"]._serialized_end = 184
    _globals["_HANDSTREAM"]._serialized_start = 186
    _globals["_HANDSTREAM"]._serialized_end = 272
# @@protoc_insertion_point(module_scope)
