# ruff: ignore
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from orca_teleop.ingress import hand_stream_pb2 as hand__stream__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in hand_stream_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class HandStreamStub:
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHandFrames = channel.stream_unary(
            "/orca_teleop.HandStream/StreamHandFrames",
            request_serializer=hand__stream__pb2.HandFrame.SerializeToString,
            response_deserializer=hand__stream__pb2.StreamSummary.FromString,
            _registered_method=True,
        )


class HandStreamServicer:
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    def StreamHandFrames(self, request_iterator, context):
        """Publisher opens a stream and continuously sends HandFrames.
        The robot responds with a summary when the stream closes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_HandStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamHandFrames": grpc.stream_unary_rpc_method_handler(
            servicer.StreamHandFrames,
            request_deserializer=hand__stream__pb2.HandFrame.FromString,
            response_serializer=hand__stream__pb2.StreamSummary.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "orca_teleop.HandStream", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("orca_teleop.HandStream", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class HandStream:
    """The single service that all publishers implement.
    Robot side runs the server; publishers connect as clients and stream frames.
    """

    @staticmethod
    def StreamHandFrames(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/orca_teleop.HandStream/StreamHandFrames",
            hand__stream__pb2.HandFrame.SerializeToString,
            hand__stream__pb2.StreamSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
