# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orca_teleop/ingress/hand_stream.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%orca_teleop/ingress/hand_stream.proto\x12\x0borca_teleop\"Z\n\x04Pose\x12\n\n\x02px\x18\x01 \x01(\x01\x12\n\n\x02py\x18\x02 \x01(\x01\x12\n\n\x02pz\x18\x03 \x01(\x01\x12\n\n\x02qw\x18\x04 \x01(\x01\x12\n\n\x02qx\x18\x05 \x01(\x01\x12\n\n\x02qy\x18\x06 \x01(\x01\x12\n\n\x02qz\x18\x07 \x01(\x01\"\xf6\x01\n\tHandFrame\x12\x11\n\tkeypoints\x18\x01 \x03(\x02\x12\x12\n\nhandedness\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\x12\x1b\n\x13wrist_angle_degrees\x18\x04 \x01(\x02\x12%\n\nwrist_pose\x18\x05 \x01(\x0b\x32\x11.orca_teleop.Pose\x12$\n\thead_pose\x18\x06 \x01(\x0b\x32\x11.orca_teleop.Pose\x12\x1b\n\x0etracking_valid\x18\x07 \x01(\x08H\x00\x88\x01\x01\x12\x12\n\npose_epoch\x18\x08 \x01(\rB\x11\n\x0f_tracking_valid\"\"\n\x0cStreamConfig\x12\x12\n\nhandedness\x18\x01 \x01(\t\"(\n\rStreamSummary\x12\x17\n\x0f\x66rames_received\x18\x01 \x01(\x03\x32V\n\nHandStream\x12H\n\x10StreamHandFrames\x12\x16.orca_teleop.HandFrame\x1a\x1a.orca_teleop.StreamSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orca_teleop.ingress.hand_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSE']._serialized_start=54
  _globals['_POSE']._serialized_end=144
  _globals['_HANDFRAME']._serialized_start=147
  _globals['_HANDFRAME']._serialized_end=393
  _globals['_STREAMCONFIG']._serialized_start=395
  _globals['_STREAMCONFIG']._serialized_end=429
  _globals['_STREAMSUMMARY']._serialized_start=431
  _globals['_STREAMSUMMARY']._serialized_end=471
  _globals['_HANDSTREAM']._serialized_start=473
  _globals['_HANDSTREAM']._serialized_end=559
# @@protoc_insertion_point(module_scope)
